/* Automatically generated by './script/bin/new.js' */
export default [
  {
    name: 'Login',
    path: '/login',
    component: 'login/login',
  },
  {
    name: 'Main',
    path: '/',
    component: 'main/main',
    children: [
      {
        name: '项目管理',
        path: 'project',
        component: 'project/project',
      },
      {
        path: '/error/:type',
        name: 'Error',
        component: 'Error', // 注意提供ErrorPage组件内的多语言翻译
      },
      {
        name: '编辑器',
        path: 'drag',
        component: 'drag/drag',
      },
      {
        name: '预览',
        path: 'preview',
        component: 'preview/preview',
      },
    ],
  },
]
