/* Automatically generated by './script/bin/new.js' */
export default [
  {
    title: '项目管理',
    router: '/project',
    icon: 'h-icon-menu',
  },
  {
    title: '编辑器',
    router: '/drag',
    icon: 'h-icon-menu',
  }
]
